trigger:
- main

pr:
  drafts: false

pool:
  vmImage: windows-latest
variables:
  major: 1
  minor: 1
  patch: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

name: $(major).$(minor).$(patch)-build$(Rev:.r) # Set the value of $(Build.BuildNumber)

steps:
- pwsh: ./download-cfcli.ps1
  displayName: Download CF Cli
    
- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '**/*.sln' 
    configuration: $(buildConfiguration)
    restoreNugetPackages: false

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test 
    projects: '**/test/*.Tests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --collect "XPlat Code Coverage" /p:CoverletOutputFormat=cobertura'
    
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: Build code coverage report
  inputs:
    reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
    targetdir: $(build.artifactstagingdirectory)/TestResults/
    reporttypes: Cobertura

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(build.artifactstagingdirectory)/TestResults/cobertura.xml

- pwsh: Rename-Item -Path "$(Build.SourcesDirectory)\src\VisualStudioExtension\src\bin\2022\$(buildConfiguration)\Tanzu.Toolkit.VisualStudio.2022.vsix" -NewName "Tanzu.Toolkit.VisualStudio.2022.$(Build.BuildNumber).vsix"
  displayName: Include version in vsix name

- publish: src/VisualStudioExtension/src/bin/2022/$(buildConfiguration)/Tanzu.Toolkit.VisualStudio.2022.$(Build.BuildNumber).vsix
  artifact: Tanzu.Toolkit.VS2022
  displayName: Publish vsix
