trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
# NuGet tool installer
# Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.x'
  inputs:
    versionSpec: 5.8.x

# NuGet
# Restore, pack, or push NuGet packages, or run a NuGet command. 
# Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. 
# Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
- task: NuGetCommand@2
  inputs:
    command: 'restore' 
    restoreSolution: '**/*.sln'
    restoreDirectory: # If no folder is specified, packages are restored into a packages/ folder alongside the selected solution

# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  inputs:
    solution: '**/*.sln' 
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test 
    projects: '**/test/*.Tests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --collect "XPlat Code Coverage" /p:CoverletOutputFormat=cobertura'
    
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  inputs:
    reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
    targetdir: $(build.artifactstagingdirectory)/TestResults/
    reporttypes: Cobertura

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage Results
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(build.artifactstagingdirectory)/TestResults/cobertura.xml

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src/VisualStudioExtension/src/bin/$(buildConfiguration)/Tanzu.Toolkit.VisualStudio.vsix'
    ArtifactName: 'Tanzu.Toolkit.VisualStudio.vsix'
