trigger:
- main

pr:
  drafts: false

strategy:
  matrix:
    Visual Studio 2019:
      VsTargetVersion: '2019'
      imageName: windows-2019
    Visual Studio 2022:
      VsTargetVersion: '2022'
      imageName: windows-2022
pool:
  vmImage: $(imageName)
variables:
  major: 1
  minor: 0
  patch: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

name: $(major).$(minor).$(patch)-build$(Rev:.r) # Set the value of $(Build.BuildNumber)

steps:
  # Run PowerShell script to sync vsix version with build number
- task: PowerShell@2
  displayName: Update version in the vsix manifest
  inputs:
    filePath: build\update-version.ps1
    arguments: $(Build.BuildNumber)
    pwsh: true

# Default NuGet version is 4.1.0 so target something newer
- task: NuGetToolInstaller@1
  displayName: Specify NuGet version
  inputs:
    versionSpec: 6.x

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '**/*.sln' 
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test 
    projects: '**/test/*.Tests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --collect "XPlat Code Coverage" /p:CoverletOutputFormat=cobertura'
    
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: Build code coverage report
  condition: eq(variables['VsTargetVersion'], '2022')
  inputs:
    reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
    targetdir: $(build.artifactstagingdirectory)/TestResults/
    reporttypes: Cobertura

- task: PublishCodeCoverageResults@1
  condition: eq(variables['VsTargetVersion'], '2022')
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(build.artifactstagingdirectory)/TestResults/cobertura.xml

- pwsh: Rename-Item -Path "$(Build.SourcesDirectory)\src\VisualStudioExtension\src\bin\$(VsTargetVersion)\$(buildConfiguration)\Tanzu.Toolkit.VisualStudio.$(VsTargetVersion).vsix" -NewName "Tanzu.Toolkit.VisualStudio.$(VsTargetVersion).$(Build.BuildNumber).vsix"
  displayName: Include version in vsix name

- publish: src/VisualStudioExtension/src/bin/$(VsTargetVersion)/$(buildConfiguration)/Tanzu.Toolkit.VisualStudio.$(VsTargetVersion).$(Build.BuildNumber).vsix
  artifact: Tanzu.Toolkit.VS$(VsTargetVersion)
  displayName: Publish vsix
