trigger:
- main

pr:
  drafts: false

strategy:
  matrix:
    VS2019:
      VsTargetVersion: VS2019
      imageName: windows-2019
    VS2022:
      VsTargetVersion: VS2022
      imageName: windows-2022
pool:
  vmImage: $(imageName)
variables:
  major: 0
  minor: 0
  patch: 4 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

name: $(major).$(minor).$(patch)-build$(Rev:.r) # Set the value of $(Build.BuildNumber)

steps:
  # Run PowerShell script to sync vsix version with build number
- task: PowerShell@2
  displayName: Update version in the vsix manifest
  inputs:
    filePath: build\update-version.ps1
    arguments: $(Build.BuildNumber)
    pwsh: true

# Default NuGet version is 4.1.0 so target something newer
- task: NuGetToolInstaller@1
  displayName: Update NuGet Tool
  inputs:
    versionSpec: 6.x

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  inputs:
    solution: '**/*.sln' 
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test 
    projects: '**/test/*.Tests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --collect "XPlat Code Coverage" /p:CoverletOutputFormat=cobertura'
    
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  condition: eq(variables['VsTargetVersion'], 'VS2022')
  inputs:
    reports: $(Agent.TempDirectory)/**/coverage.cobertura.xml
    targetdir: $(build.artifactstagingdirectory)/TestResults/
    reporttypes: Cobertura

- task: PublishCodeCoverageResults@1
  condition: eq(variables['VsTargetVersion'], 'VS2022')
  displayName: Publish Code Coverage Results
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(build.artifactstagingdirectory)/TestResults/cobertura.xml

- pwsh: Rename-Item -Path "$(Build.SourcesDirectory)\src\VisualStudioExtension\src\bin\$(VsTargetVersion)\$(buildConfiguration)\Tanzu.Toolkit.VisualStudio.vsix" -NewName "Tanzu.Toolkit.VisualStudio.$(Build.BuildNumber).vsix"
  displayName: Rename vsix file to include version number

- publish: src/VisualStudioExtension/src/bin/$(VsTargetVersion)/$(buildConfiguration)/Tanzu.Toolkit.VisualStudio.$(Build.BuildNumber).vsix
  artifact: Tanzu.Toolkit.$(VsTargetVersion)
