trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:

# NuGet
# Restore, pack, or push NuGet packages, or run a NuGet command. 
# Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. 
# Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
- task: NuGetCommand@2
  inputs:
    command: 'restore' 
    restoreSolution: '**/*.sln'
    restoreDirectory: # If no folder is specified, packages are restored into a packages/ folder alongside the selected solution

# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 

# Visual Studio Test
# Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner.
# Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run.
# Tests can be distributed on multiple agents using this task (version 2).
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*test*.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
