trigger: none

pr: none

schedules:
- cron: "0 9 * * 1,3,5" # every Monday, Wednesday, and Friday at 9:00 AM
  displayName: CF environment renewal
  always: true
  branches:
    include:
      - 'main'
pool:
  vmImage: ubuntu-latest

steps:
- bash: curl -v https://environments.toolsmiths.cf-app.com/custom_gcp_environments/465/renew
