// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tanzu.Toolkit.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "TanzuToolkitForVisualStudio2022.ff7b6f3e-0410-4ff9-a40a-a719ee9da901";
        public const string Name = "Tanzu Toolkit for Visual Studio 2022";
        public const string Description = @"Administer your Tanzu Platform environment directly from within Visual Studio! ";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "VMware Tanzu .NET Experience";
        public const string Tags = "";
    }
}
