// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tanzu.Toolkit.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "TanzuToolkitForVisualStudio2022.ff7b6f3e-0410-4ff9-a40a-a719ee9da901";
        public const string Name = "Tanzu Toolkit for Visual Studio 2022";
        public const string Description = @"Deploy, debug and manage your apps on Tanzu Platform from within Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "VMware Tanzu .NET Experience";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
