// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tanzu.Toolkit.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTanzuToolkitPackageString = "9419e55b-9e82-4d87-8ee5-70871b01b7cc";
        public static Guid guidTanzuToolkitPackage = new Guid(guidTanzuToolkitPackageString);

        public const string guidTanzuToolkitPackageCmdSetString = "f91c88fb-6e17-42a6-878d-f4d16ead7625";
        public static Guid guidTanzuToolkitPackageCmdSet = new Guid(guidTanzuToolkitPackageCmdSetString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);

        public const string guidImagesString = "99936759-85d4-4db9-8ac2-ca1402b12ad4";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "1e401806-768f-42f2-af53-6e1281da6f5e";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TasExplorerCommandId = 0x0100;
        public const int PushToCloudFoundryCommandId = 0x0101;
        public const int RequestFeedbackCommandId = 0x0102;
        public const int OpenLogsCommandId = 0x0103;
        public const int RemoteDebugId = 0x0104;
        public const int ProjContextMenuGroup = 0x03E9;
        public const int ViewMenuGroup = 0x03EA;
        public const int ExtensionsMenuGroup = 0x1020;
        public const int TanzuToolkitMenu = 0x1022;
        public const int ToolkitExtSubmenuGroup = 0x1023;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0001;
    }
}