using System.IO;

namespace Tanzu.Toolkit.VisualStudio.Services.Tests.CfCli
{
    public class CfCliServiceTestSupport : ServicesTestSupport
    {
        internal const string _fakeOrgName1 = "autogenerated-org-1";
        internal const string _fakeOrgGuid1 = "e9519220-89fb-46cc-93b0-8e6ea9e264b2";
        internal const string _fakeSpaceName1 = "autogenerated-space-1";
        internal const string _fakeSpaceGuid1 = "b008f4c6-5a4d-4ed0-880f-f0eb57de95eb";

        internal static readonly string _fakeMultiPageOrgsOutput = File.ReadAllText("CfCli/FakeMultiPageOrgsOutput.txt");
        internal static readonly string _fakeNoOrgsOutput = File.ReadAllText("CfCli/FakeNoOrgsOutput.txt");
        internal static readonly string _fakeMultiPageSpacesOutput = File.ReadAllText("CfCli/FakeMultiPageSpacesOutput.txt");
        internal static readonly string _fakeNoSpacesOutput = File.ReadAllText("CfCli/FakeNoSpacesOutput.txt");
    }
}
