using System.IO;

namespace Tanzu.Toolkit.VisualStudio.Services.Tests.CfCli
{
    public class CfCliServiceTestSupport : ServicesTestSupport
    {
        internal const string _fakeOrgName1 = "autogenerated-org-1";
        internal const string _fakeOrgGuid1 = "e9519220-89fb-46cc-93b0-8e6ea9e264b2";
        internal const string _fakeSpaceName1 = "autogenerated-space-1";
        internal const string _fakeSpaceGuid1 = "b008f4c6-5a4d-4ed0-880f-f0eb57de95eb";
        internal const string _fakeCurledSpaceName1 = "test-space-3-1";
        internal const string _fakeCurledSpaceGuid1 = "69cc0abb-296e-4c47-9701-9368a1570f38";
        internal const string _fakeAppName1 = "sample-app";
        internal const string _fakeAppGuid1 = "75b5b69b-2b58-46b0-b01c-3aa1b6b891e8";

        internal static readonly string _fakeMultiPageOrgsOutput = File.ReadAllText("CfCli/FakeMultiPageOrgsOutput.txt");
        internal static readonly string _fakeNoOrgsOutput = File.ReadAllText("CfCli/FakeNoOrgsOutput.txt");
        internal static readonly string _fakeMultiPageSpacesOutput = File.ReadAllText("CfCli/FakeMultiPageSpacesOutput.txt");
        internal static readonly string _fakeNoSpacesOutput = File.ReadAllText("CfCli/FakeNoSpacesOutput.txt");
        internal static readonly string _fakeManyAppsOutput = File.ReadAllText("CfCli/FakeManyAppsOutput.txt");
        internal static readonly string _fakeNoAppsOutput = File.ReadAllText("CfCli/FakeNoAppsOutput.txt");
        internal static readonly string _fakeCurlSpacesOutput = File.ReadAllText("CfCli/FakeCurlSpacesOutput.txt");

        internal static readonly int numOrgsInFakeResponse = 54;
        internal static readonly int numSpacesInFakeResponse = 54;

    }
}
